apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator

metadata:
  name: logging-policy-generator

policyDefaults:
  remediationAction: enforce
  namespace: hub-cluster-infra
  placement:
    placementName: hub-cluster-infra

placementBindingDefaults:
  name: binding-logging-policy-generator

policies:
  - name: logging-policy
    manifests:
      - path: manifests