apiVersion: loki.grafana.com/v1
kind: LokiStack
metadata:
  annotations:
  name: logging-loki
  namespace: openshift-logging
spec:
  size: 1x.pico
  storageClassName: thin-csi
  tenants:
    mode: openshift-logging
  managementState: Managed
  rules:
    enabled: true
  limits:
    global:
      ingestion:
        ingestionBurstSize: 16
        ingestionRate: 8
        maxGlobalStreamsPerTenant: 10000
        maxLabelNameLength: 1024
        maxLabelNamesPerSeries: 30
        maxLabelValueLength: 2048
        maxLineSize: 256000
      queries:
        maxChunksPerQuery: 2000000
        maxEntriesLimitPerQuery: 10000
        maxQuerySeries: 1000
        queryTimeout: 1m
      retention:
        days: 2
  template:
    compactor:
      nodeSelector:
        node-role.kubernetes.io/infra: ''
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/logging
          value: reserved
        - effect: NoExecute
          key: node-role.kubernetes.io/logging
          value: reserved
    distributor:
      nodeSelector:
        node-role.kubernetes.io/infra: ''
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/logging
          value: reserved
        - effect: NoExecute
          key: node-role.kubernetes.io/logging
          value: reserved
    gateway:
      nodeSelector:
        node-role.kubernetes.io/infra: ''
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/logging
          value: reserved
        - effect: NoExecute
          key: node-role.kubernetes.io/logging
          value: reserved
    indexGateway:
      nodeSelector:
        node-role.kubernetes.io/infra: ''
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/logging
          value: reserved
        - effect: NoExecute
          key: node-role.kubernetes.io/logging
          value: reserved
    ingester:
      nodeSelector:
        node-role.kubernetes.io/infra: ''
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/logging
          value: reserved
        - effect: NoExecute
          key: node-role.kubernetes.io/logging
          value: reserved
    querier:
      nodeSelector:
        node-role.kubernetes.io/infra: ''
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/logging
          value: reserved
        - effect: NoExecute
          key: node-role.kubernetes.io/logging
          value: reserved
    queryFrontend:
      nodeSelector:
        node-role.kubernetes.io/infra: ''
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/logging
          value: reserved
        - effect: NoExecute
          key: node-role.kubernetes.io/logging
          value: reserved
    ruler:
      nodeSelector:
        node-role.kubernetes.io/infra: ''
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/logging
          value: reserved
        - effect: NoExecute
          key: node-role.kubernetes.io/logging
          value: reserved
  replicationFactor: 1
  storage:
    schemas:
      - effectiveDate: '2022-06-21'
        version: v13
    secret:
      name: logging-loki-s3
      type: s3
    tls:
      caName: openshift-service-ca.crt