apiVersion: v1
kind: Secret
metadata:
  name: logging-loki-s3
  namespace: openshift-logging
type: Opaque
stringData:
  access_key_id: sbtWE7V94KKC1VGpFuMR
  access_key_secret: 'EvN7WfW+sGcv6ulHzxsA/Bftb7155azoJCqQtReZ'
  bucketnames: loki-9987c6d0-b401-489a-b461-5adc869c44df
  endpoint: https://s3.openshift-storage.svc:443