apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator

metadata:
  name: machine-set-infra-logging-policy-generator

policyDefaults:
  remediationAction: enforce
  namespace: hub-cluster-infra
  placement:
    placementName: hub-cluster-infra

placementBindingDefaults:
  name: binding-machine-set-infra-logging

policies:
  - name: machine-set-infra-logging
    manifests:
      - path: manifests