apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator

metadata:
  name: machine-set-worker-policy-generator

policyDefaults:
  remediationAction: enforce
  namespace: hub-cluster-infra
  placement:
    placementName: hub-cluster-infra

placementBindingDefaults:
  name: binding-machine-set-worker

policies:
  - name: machine-set-worker
    manifests:
      - path: manifests