apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - etcd-backup
  - machine-set-infra
  - machine-set-infra-logging
  - machine-set-infra-storage
  # - monitoring
  - oauth
  - ingress-controller-default
  # - image-registry
  - operators
  - logging